from skopt.space import Real, Integer


# define the hyperparameter search space
space = [
    Real(
        low=10**-3,
        high=10**-1,
        prior='log-uniform',
        name='learning_rate'),
    Integer(
        low=16,
        high=28,
        name='num_filters'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_1_1'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_1_2'),
    Integer(
        low=9,
        high=12,
        name='kernel_size_1_3'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_2_1'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_2_2'),
    Integer(
        low=9,
        high=12,
        name='kernel_size_2_3'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_3_1'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_3_2'),
    Integer(
        low=9,
        high=12,
        name='kernel_size_3_3'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_4_1'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_4_2'),
    Integer(
        low=9,
        high=12,
        name='kernel_size_4_3'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_5_1'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_5_2'),
    Integer(
        low=9,
        high=12,
        name='kernel_size_5_3'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_6_1'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_6_2'),
    Integer(
        low=9,
        high=12,
        name='kernel_size_6_3'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_7_1'),
    Integer(
        low=9,
        high=15,
        name='kernel_size_7_2'),
    Integer(
        low=9,
        high=12,
        name='kernel_size_7_3'),
    Real(
        low=0.5,
        high=0.6,
        prior='log-uniform',
        name='overlap'),
    Integer(
        low=64,
        high=2048,  # bounds from [Hammerla & al. 2016]
        name='num_units_dense_layer'),
    Real(
        low=0.1,
        high=0.5,
        prior='log-uniform',
        name='dropout')
]
